sudo: required
dist: trusty
language: crystal
env:
  global:
        - LIBSNDFILE_URL="http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.26.tar.gz"

addons:
  apt:
    packages:
      - libvorbis-dev
      - libflac-dev
      - libasound2-dev

install:
  ## build libsndfile
  - mkdir -p libsndfile/build && curl "$LIBSNDFILE_URL" | tar --strip-components=1 -C libsndfile -xvzf -
  - cd libsndfile/build && ../configure --disable-silent-rules && make && sudo make install
  #  ## remove libtool libs
  #  - find /usr/local/lib -type f -name "*.la" -exec sudo rm -f {} \+

script:
  - crystal spec spec/soundfile_spec.cr
